---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The problem of determining the most important target of a vaccination strategy goes beyond the bounds of statistics and into the realm of politics. We, accordingly, did not feel that it was our place to declare what in particular a "best" approach should seek to accomplish. Instead, we allow the simulation user to define their own priorities for the outcome according to the formula
$$
T = 100 \times (P_CR_C + P_DR_D)
$$
where $T$ is the target metric, $P_C$ and $P_D$, $0 \leq P_C, P_D \leq 1$, are the user-selected weights for improving case load and mortality, respectively, and $R_C$ and $R_D$ are the percent reductions in cases and deaths, respectively, compared to an average simulation with no vaccination. This statistic represents a weighted percent improvement in pandemic handling compared to a scenario where no vaccines are distributed.

The reference "average simulation" was determined by simulating the pandemic's progression without vaccine intervention 10,000 times and finding the mean number of total cases and total deaths.